import { Router } from "express";
import { authRouter } from "./auth";
import { childrenRouter } from "./children";
import { progressRouter } from "./progress";
import { adminRouter } from "./admin";
import { usersRouter } from "./users";
import { resourcesRouter } from "./resources";
import { checkInsRouter } from "./checkIns";
import { supervisionLogsRouter } from "./supervisionLogs";
import { trainingRouter } from "./training";
import { orgRouter } from "./org";
import { directoryRouter } from "./directory";
import { exportsRouter } from "./exports";
import { trainerDashboardRouter } from "./trainerDashboard";
import { invitationsRouter } from "./invitations";
import { accessibilityRouter } from "./accessibility";
import { uploadRouter } from "./upload";

export const router = Router();

router.use("/auth", authRouter);
router.use("/children", childrenRouter);
router.use("/progress", progressRouter);
router.use("/admin", adminRouter);
router.use("/users", usersRouter);
router.use("/resources", resourcesRouter);
router.use("/check-ins", checkInsRouter);
router.use("/supervision-logs", supervisionLogsRouter);
router.use("/training", trainingRouter);
router.use("/org", orgRouter);
router.use("/directory", directoryRouter);
router.use("/exports", exportsRouter);
router.use("/trainer", trainerDashboardRouter);
router.use("/invitations", invitationsRouter);
router.use("/accessibility", accessibilityRouter);
router.use("/upload", uploadRouter);
